services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www:delegated
            - /var/www/vendor
            - /var/www/node_modules
        networks:
            - laravel
        depends_on:
            - mysql
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:Qqo1U2BcoP69mdXEc1Grk3AJ17bX0C7/tBJ+Lnl4L+0=
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel_db
            - DB_USERNAME=root
            - DB_PASSWORD=root

    mysql:
        image: mysql:8
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www:delegated
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - laravel
        depends_on:
            - app

volumes:
    mysql_data:

networks:
    laravel:
